Repository tikv/raft-rs, pull requests merged in 2018-09, with the labels that each got.

#106 Some additional documentation.
  src/eraftpb.rs
  src/errors.rs
  src/lib.rs
  src/raft.rs
  src/raw_node.rs
  src/read_only.rs
  tests/tests.rs
Labels: enhancement

#110 Introduce benchmarking using Criterion.
  Cargo.toml
  README.md
  benches/benches.rs
  benches/suites/mod.rs
  benches/suites/progress.rs
  benches/suites/progress_set.rs
  benches/suites/raft.rs
  benches/suites/raw_node.rs
  src/lib.rs
  src/raft.rs
Labels: enhancement

#117 Refine CI script to ensure correctness.
  .travis.yml
Labels: Tooling/Testing

#118 Improve examples in documentation.
  src/lib.rs
Labels: Documentation

#114 tests: use fail point
  .travis.yml
  Cargo.toml
  examples/single_mem_node/main.rs
  src/lib.rs
  src/raft.rs
  src/raw_node.rs
  src/util.rs
  tests/failpoint_cases/mod.rs
  tests/integration_cases/mod.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_flow_control.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raft_snap.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
  tests/tests.rs
Labels: Tooling/Testing

#124 Use the newly available stable clippy. Fix lints.
  .travis.yml
  README.md
  benches/benches.rs
  benches/suites/progress.rs
  benches/suites/raft.rs
  benches/suites/raw_node.rs
  rust-toolchain
  src/eraftpb.rs
  src/errors.rs
  src/lib.rs
  src/progress.rs
  src/raft.rs
  src/raft_log.rs
  src/raw_node.rs
  src/storage.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
  tests/tests.rs
Labels: Tooling/Testing

#126 Add siddon's talk
  README.md
Labels: Documentation

#108 Use a single set of Progresses for ProgressSet.
  benches/suites/progress_set.rs
  src/progress.rs
  src/raft.rs
  src/raw_node.rs
  src/status.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_flow_control.rs
  tests/integration_cases/test_raft_snap.rs
  tests/test_util/mod.rs
  tests/tests.rs
Labels: Enhancement, Feature
