Repository tikv/raft-rs, pull requests merged in 2019-04, with the labels that each got.

#201 Replace rust-protobuf with prost
  Cargo.toml
  build.rs
  examples/five_mem_node/main.rs
  generate-proto.sh
  src/eraftpb.rs
  src/errors.rs
  src/lib.rs
  src/log_unstable.rs
  src/prost.rs
  src/prost/eraftpb.rs
  src/prost/wrapper_eraftpb.rs
  src/raft.rs
  src/raft_log.rs
  src/raw_node.rs
  src/storage.rs
  src/util.rs
  tests/integration_cases/test_membership_changes.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
Labels: Feature

#215 Regenerate wrapper with latest kvproto-build
  Cargo.toml
  build.rs
  src/prost/wrapper_eraftpb.rs
  src/raft.rs
Labels: Enhancement

#204 Porting prost migration to raft 0.4
  .gitignore
  Cargo.toml
  benches/benches.rs
  benches/suites/progress_set.rs
  benches/suites/raft.rs
  build.rs
  examples/single_mem_node/main.rs
  generate-proto.sh
  src/eraftpb.rs
  src/errors.rs
  src/lib.rs
  src/log_unstable.rs
  src/progress.rs
  src/prost.rs
  src/prost/eraftpb.rs
  src/prost/wrapper_eraftpb.rs
  src/raft.rs
  src/raft_log.rs
  src/raw_node.rs
  src/read_only.rs
  src/status.rs
  src/storage.rs
  src/util.rs
  tests/failpoint_cases/mod.rs
  tests/integration_cases/mod.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_flow_control.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raft_snap.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
  tests/tests.rs
Labels: Do Not Merge

#227 Add more convenient lite-weight interfaces
  src/lib.rs
  src/raft.rs
  src/raw_node.rs
  src/status.rs
Labels: Enhancement

#220 raft: leader respond to learner read index message
  src/raft.rs
  tests/integration_cases/test_raft.rs
Labels: Bug
