Repository tikv/raft-rs, pull requests merged in 2019-05, with the labels that each got.

#230 *: tiny refactor
  src/raft.rs
  src/raw_node.rs
  src/status.rs
Labels: Enhancement

#233 Ease protobuf dependency
  Cargo.toml
Labels: Enhancement

#232 Don't cache all of the cargo caches.
  .travis.yml
Labels: Tooling/Testing

#240 Add deps.rs badge, upgrade some outdated dependencies
  Cargo.toml
  README.md
  harness/Cargo.toml
Labels: Documentation
