Repository tikv/raft-rs, pull requests merged in 2019-02, with the labels that each got.

#180 Fix feature so it functions on stable
  src/lib.rs
  src/raft.rs
  src/raw_node.rs
Labels: Bug, Tooling/Testing

#181 Ease protobuf dependency to match kvproto
  Cargo.toml
Labels: Bug

#171 add a new example for 5 nodes.
  Cargo.toml
  examples/five_mem_node/main.rs
Labels: Tooling/Testing

#127 Extract Network and Interface from utils
  .gitignore
  Cargo.toml
  harness/Cargo.toml
  harness/src/interface.rs
  harness/src/lib.rs
  harness/src/network.rs
  src/errors.rs
  src/lib.rs
  src/log_unstable.rs
  src/progress.rs
  src/raft_log.rs
  src/raw_node.rs
  src/storage.rs
  tests/failpoint_cases/mod.rs
  tests/integration_cases/test_membership_changes.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_flow_control.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raft_snap.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
  tests/tests.rs
Labels: Enhancement

#184 Update to Rust 2018
  .gitignore
  Cargo.toml
  benches/benches.rs
  benches/suites/progress_set.rs
  benches/suites/raft.rs
  examples/single_mem_node/main.rs
  generate-proto.sh
  rust-toolchain
  src/eraftpb.rs
  src/errors.rs
  src/lib.rs
  src/log_unstable.rs
  src/progress.rs
  src/raft.rs
  src/raft_log.rs
  src/raw_node.rs
  src/read_only.rs
  src/status.rs
  src/storage.rs
  src/util.rs
  tests/failpoint_cases/mod.rs
  tests/integration_cases/test_membership_changes.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_flow_control.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raft_snap.rs
  tests/integration_cases/test_raw_node.rs
  tests/tests.rs
Labels: Feature

#169 Fix ReadIndex request dropping issue
  src/raft.rs
  tests/integration_cases/test_raft.rs
Labels: Bug

#179 batch MsgAppend entries
  src/config.rs
  src/progress.rs
  src/raft.rs
  src/raw_node.rs
  src/util.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_paper.rs
Labels: Feature
