Repository tikv/raft-rs, pull requests merged in 2019-01, with the labels that each got.

#142 Fix lints
  benches/benches.rs
  benches/suites/progress_set.rs
  examples/single_mem_node/main.rs
  src/eraftpb.rs
  src/errors.rs
  src/progress.rs
  src/raft.rs
  src/raft_log.rs
  src/raw_node.rs
  src/util.rs
  tests/integration_cases/test_raft.rs
  tests/integration_cases/test_raft_paper.rs
  tests/integration_cases/test_raw_node.rs
  tests/test_util/mod.rs
Labels: Tooling/Testing

#160 Update fxhash Hashes to hashbrown Hashes
  Cargo.toml
  src/lib.rs
  src/progress.rs
  src/raft.rs
  src/read_only.rs
  src/status.rs
  tests/integration_cases/test_raft.rs
  tests/tests.rs
Labels: Enhancement

#165 Correct learner checking in handle_transfer_leader
  src/raft.rs
  tests/integration_cases/test_raft.rs
Labels: Bug

#168 Resolve some clippy lints
  Cargo.toml
  src/eraftpb.rs
  src/raft.rs
Labels: Tooling/Testing

#138 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation
